#!/usr/bin/env bash
# This script installs and configures HAProxy to load balance traffic between web-01 and web-02

# Check if the script is running as root
if [ "$(id -u)" -ne 0 ]; then
    echo "The script is not running as root. Re-executing with sudo..."
    exec sudo bash "$0" "$@"
fi

# Update package list and install HAProxy
apt-get update -y
apt-get install -y haproxy

# Enable HAProxy to start on boot
systemctl enable haproxy

# Configure HAProxy
HA_PROXY_CONF="/etc/haproxy/haproxy.cfg"

# Backup the original HAProxy configuration file
cp $HA_PROXY_CONF $HA_PROXY_CONF.bak

# Write the new HAProxy configuration
cat <<EOL > $HA_PROXY_CONF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web1 100.26.216.113:80 check
    server web2 34.204.60.227:80 check
EOL

# Restart HAProxy to apply the new configuration
systemctl restart haproxy
