#!/usr/bin/env bash
# This script configures Nginx to listen on port 80 and restarts the Nginx service

# Install Nginx if not already installed
apt-get update
apt-get install -y nginx

# Remove default Nginx configuration file
rm /etc/nginx/sites-enabled/default

NGINX_CONF="/etc/nginx/sites-available/default"
NGINX_LINK="/etc/nginx/sites-enabled/default"

ln -s $NGINX_CONF $NGINX_LINK

# Restart Nginx to apply the changes
systemctl restart nginx
