#!/usr/bin/env bash
# This script configures Nginx to listen on port 80 and restarts the Nginx service

# Remove default Nginx configuration file
sudo rm -f /etc/nginx/sites-enabled/default

# Create new symbolic link for Nginx configuration file
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo service nginx restart
